name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC
  workflow_dispatch:      # Allows manual trigger from GitHub

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: cluo0005
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
      - name: Commit and Push the generated files
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git clone https://github.com/${{ github.repository }} repo
          cd repo
          mkdir -p dist
          cp ../dist/* ./dist/
          git add dist
          git commit -m "Update Snake animation"
          git push
